apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  template:
    metadata:
      name: gateway
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          # image: breed_gateway for local testing
          image: 337330634567.dkr.ecr.us-east-1.amazonaws.com/ml-zoomcamp:gateway-001
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "0.5"
              memory: 128Mi
            requests:
              cpu: "0.5"
              memory: 128Mi
          ports:
            - containerPort: 9696
          env:
            - name: BREED_MODEL_URL
              value: tf-serving-cat-breeds-model.default.svc.cluster.local:8500
      restartPolicy: Always
  selector:
    matchLabels:
      app: gateway
